Downloading https://www.scribd.com/document/797386368/MS-CS-Handbook-24-25-Final
Downloading https://lti.cmu.edu/academics/masters-programs/files/mcds-handbook-ay-25-26.pdf
Downloading https://www.cmu.edu/ini/student-services/enrollment/enrollment_docs/ini_student_handbook_ms36_8.20.25_final.pdf
Downloading https://ml.cmu.edu/current-students/ml-masters-handbook-fall2024.pdf
Downloading https://www.ri.cmu.edu/app/uploads/2024/09/MSCV-Handbook-2024-25.pdf
Downloading https://lti-web-prod-vip.andrew.cmu.edu/academics/masters-programs/files/miis-handbook-2025-2026-final2.pdf
Downloading https://www.ri.cmu.edu/app/uploads/2024/09/MSCV-Handbook-2024-25.pdf
Downloading https://hcii.cmu.edu/sites/default/files/2024-10/MHCI-Student-Handbook-24-25.pdf
Downloading https://mse.s3d.cmu.edu/0_documents/ay23-24-mse-student-handbook-final.pdf
Downloading https://mse.s3d.cmu.edu/0_documents/mse-final-masters-student-handbook-ay-24-25.pdf
Downloading https://www.cmu.edu/compbio/current-student-resources/cpcb-handbook-2025.pdf
Downloading https://grad.illinois.edu/document/handbook
Downloading https://grad.illinois.edu/document/handbook
Downloading https://grad.illinois.edu/document/handbook
Downloading https://grad.illinois.edu/document/handbook
Downloading https://web.cs.toronto.edu/graduate/forms-and-handbooks
Downloading https://www.ece.ucsd.edu/sites/default/files/research-areas/CE%20%28EC79%29%202024%20-%202025%20-%20Fillable.pdf
Downloading https://datascience.ucsd.edu/wp-content/uploads/2023/11/MS-Student-Handbook-AY23-24.pdf
Traceback (most recent call last):
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/connection.py", line 969, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/.pyenv/versions/3.11.9/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/.pyenv/versions/3.11.9/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/tanmay1024/.pyenv/versions/3.11.9/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='datascience.ucsd.edu', port=443): Max retries exceeded with url: /wp-content/uploads/2023/11/MS-Student-Handbook-AY23-24.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_downloader.py", line 22, in <module>
    main()
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_downloader.py", line 19, in main
    f_out.write(requests.get(pdf_url).content)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanmay1024/Projects/PDF_crawler/pdf_finder/lib/python3.11/site-packages/requests/adapters.py", line 675, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='datascience.ucsd.edu', port=443): Max retries exceeded with url: /wp-content/uploads/2023/11/MS-Student-Handbook-AY23-24.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
